- hosts: web
  tasks:
    - name: "install apache web server"
      package:
        name: "httpd"
        state: present
    - name: "install php server"
      package:
        name: "php"
        state: present
    - name: "Deploy Web Page"
      copy:
        src: "index.php"
        dest: "/var/www/html"
    - name: "start web service"
      service:
        name: "httpd"
        state: started
